services:
  clash-checker:
    build: .
    image: clash-checker
    ports:
      - "8000:8000"
    volumes:
      - ./data:/root/.config/mihomo/data
      # - .:/app
    environment:
      - TZ=Asia/Shanghai
      - DATA_DIR=/root/.config/mihomo/data
    restart: always
